## to test access 
## 
# Now go to: http://localhost
# Check backends health at: http://admin:admin@localhost:1936
#

version: "2"
services:
  haproxy:
    image: bugre/haproxy
    depends_on:
    - webapp
    ports:
    - "80:8080"
    - "1936:1936"
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS: "webapp"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      HTTPCHK_HOST: "myhost.com"
      INTER: "5s"
      LOG_LEVEL: "debug"
  webapp:
    image: bugre/helloworld-py
    environment:
      PORT: "8080"
